/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.ltp3.trabalhoFinal.interfaceUsuario;

/**
 *
 *
 */
public class frmBody extends javax.swing.JFrame {

    /**
     * Creates new form frmBody
     */
    public frmBody() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrnBodyCapa = new javax.swing.JPanel();
        btnBodyAluno = new javax.swing.JButton();
        btnBodyOrientador = new javax.swing.JButton();
        btnBodyProjeto = new javax.swing.JButton();
        btnBodyRelatorio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmBodyCadastrar = new javax.swing.JMenu();
        jmBodyListar = new javax.swing.JMenu();
        jmBodyProjetos = new javax.swing.JMenu();
        jmBodyRelarotio = new javax.swing.JMenu();
        jmBodyUsuario = new javax.swing.JMenu();
        jmBodySobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jrnBodyCapa.setBackground(new java.awt.Color(255, 255, 255));

        btnBodyAluno.setText("Aluno");

        btnBodyOrientador.setText("Orientador");

        btnBodyProjeto.setText("Projeto");

        btnBodyRelatorio.setText("Relatorios");

        javax.swing.GroupLayout jrnBodyCapaLayout = new javax.swing.GroupLayout(jrnBodyCapa);
        jrnBodyCapa.setLayout(jrnBodyCapaLayout);
        jrnBodyCapaLayout.setHorizontalGroup(
            jrnBodyCapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jrnBodyCapaLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(jrnBodyCapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBodyOrientador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBodyProjeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jrnBodyCapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBodyAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBodyRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
        );
        jrnBodyCapaLayout.setVerticalGroup(
            jrnBodyCapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jrnBodyCapaLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jrnBodyCapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBodyAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBodyOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jrnBodyCapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBodyRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBodyProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 204, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jmBodyCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jmBodyCadastrar.setText("Cadastrar");
        jMenuBar1.add(jmBodyCadastrar);

        jmBodyListar.setForeground(new java.awt.Color(255, 255, 255));
        jmBodyListar.setText("Listar");
        jMenuBar1.add(jmBodyListar);

        jmBodyProjetos.setForeground(new java.awt.Color(255, 255, 255));
        jmBodyProjetos.setText("Projetos");
        jMenuBar1.add(jmBodyProjetos);

        jmBodyRelarotio.setForeground(new java.awt.Color(255, 255, 255));
        jmBodyRelarotio.setText("Relatorios");
        jMenuBar1.add(jmBodyRelarotio);

        jmBodyUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jmBodyUsuario.setText("Usuario");
        jMenuBar1.add(jmBodyUsuario);

        jmBodySobre.setForeground(new java.awt.Color(255, 255, 255));
        jmBodySobre.setText("Sobre");
        jMenuBar1.add(jmBodySobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jrnBodyCapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jrnBodyCapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBody().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBodyAluno;
    private javax.swing.JButton btnBodyOrientador;
    private javax.swing.JButton btnBodyProjeto;
    private javax.swing.JButton btnBodyRelatorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmBodyCadastrar;
    private javax.swing.JMenu jmBodyListar;
    private javax.swing.JMenu jmBodyProjetos;
    private javax.swing.JMenu jmBodyRelarotio;
    private javax.swing.JMenu jmBodySobre;
    private javax.swing.JMenu jmBodyUsuario;
    private javax.swing.JPanel jrnBodyCapa;
    // End of variables declaration//GEN-END:variables
}
